import React, { useState } from 'react';
import { Play, Pause, SkipForward, SkipBack, ShieldCheck, CheckCircle2 } from 'lucide-react';
import { StatusBadge } from '../components/common/StatusBadge';

export const DecisionHistoryPage: React.FC = () => {
  const [isPlaying, setIsPlaying] = useState(false);
  const [currentStep, setCurrentStep] = useState(2);
  const [speed, setSpeed] = useState(1);

  const steps = [
    { idx: 0, time: '09:00:00 UTC', event: 'Initial Live State Ingested (v18400)' },
    { idx: 1, time: '09:15:00 UTC', event: 'Candidate Plans A, B, C Generated by CP-SAT' },
    { idx: 2, time: '09:30:00 UTC', event: 'Disruption Detected: Sector 4 Severe Crosswinds' },
    { idx: 3, time: '09:45:00 UTC', event: 'Re-optimization Executed: Plan Bravo Promoted' },
    { idx: 4, time: '10:00:00 UTC', event: 'Decision Authority Accepted & Digitally Signed' }
  ];

  return (
    <div className="space-y-6 font-mono select-none">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-xl font-bold tracking-tight text-[#E8EDF7]">DECISION HISTORY & REPLAY</h1>
          <p className="text-xs text-[#9AA7BF] mt-0.5">Time-Ordered Step-by-Step State Reconstruction & Signature Verification (Spec §16.5)</p>
        </div>
        <div className="flex items-center space-x-2 bg-[#142621] border border-[#22A06B]/40 px-3 py-1.5 rounded text-xs text-[#22A06B] font-bold">
          <ShieldCheck className="w-4 h-4" />
          <span>Decision Signature Verified (Ed25519)</span>
        </div>
      </div>

      {/* Replay Player Transport Toolbar */}
      <div className="bg-[#111A2E] border border-[#24304A] rounded-lg p-5 space-y-4">
        <div className="flex justify-between items-center">
          <div className="flex items-center space-x-3">
            <button
              onClick={() => setCurrentStep(Math.max(0, currentStep - 1))}
              className="p-2 rounded bg-[#172238] hover:bg-[#24304A] text-[#E8EDF7]"
            >
              <SkipBack className="w-4 h-4" />
            </button>
            <button
              onClick={() => setIsPlaying(!isPlaying)}
              className="px-4 py-2 rounded bg-[#3B82F6] hover:bg-blue-600 text-white font-bold flex items-center space-x-1.5"
            >
              {isPlaying ? <Pause className="w-4 h-4" /> : <Play className="w-4 h-4" />}
              <span>{isPlaying ? 'Pause' : 'Play Replay'}</span>
            </button>
            <button
              onClick={() => setCurrentStep(Math.min(steps.length - 1, currentStep + 1))}
              className="p-2 rounded bg-[#172238] hover:bg-[#24304A] text-[#E8EDF7]"
            >
              <SkipForward className="w-4 h-4" />
            </button>
          </div>

          <div className="flex items-center space-x-2 text-xs">
            <span className="text-[#7A869C]">Speed:</span>
            {[1, 2, 5].map((s) => (
              <button
                key={s}
                onClick={() => setSpeed(s)}
                className={`px-2.5 py-1 rounded border ${
                  speed === s ? 'bg-[#3B82F6] border-[#3B82F6] text-white' : 'border-[#24304A] text-[#9AA7BF]'
                }`}
              >
                {s}x
              </button>
            ))}
          </div>
        </div>

        {/* Timeline Scrubber */}
        <div className="space-y-2">
          <div className="flex justify-between text-xs text-[#7A869C]">
            <span>Step {currentStep + 1} of {steps.length}</span>
            <span className="text-[#3B82F6] font-bold">{steps[currentStep].time}</span>
          </div>
          <div className="grid grid-cols-5 gap-2">
            {steps.map((st) => (
              <button
                key={st.idx}
                onClick={() => setCurrentStep(st.idx)}
                className={`h-2 rounded transition-colors ${
                  st.idx === currentStep ? 'bg-[#3B82F6]' : st.idx < currentStep ? 'bg-[#22A06B]' : 'bg-[#172238]'
                }`}
              />
            ))}
          </div>
        </div>

        <div className="p-3 bg-[#0B1220] rounded border border-[#24304A] text-xs">
          <span className="text-[#3B82F6] font-bold">REPLAY STATE EVENT:</span> {steps[currentStep].event}
        </div>
      </div>
    </div>
  );
};
